# Generated by Django 6.0.2 on 2026-06-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('image_bg', models.CharField(max_length=10)),
                ('project_title', models.CharField(max_length=255)),
                ('working_date', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('link', models.TextField()),
            ],
        ),
    ]
