# Generated by Django 6.0.2 on 2026-06-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_projects_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image_bg',
            field=models.CharField(max_length=100),
        ),
    ]
