# Generated by Django 6.0.2 on 2026-06-23 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_projects_image_bg'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='github',
            field=models.TextField(blank=True),
        ),
    ]
