# Generated by Django 6.0.2 on 2026-06-30 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_projects_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(related_name='projects', to='home.skills'),
        ),
    ]
