# Generated by Django 5.2.16 on 2026-09-11 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_category_id_alter_projects_id_alter_skills_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='image',
            field=models.URLField(),
        ),
    ]
