# Generated by Django 5.2.16 on 2026-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_skills_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skills',
            name='image',
            field=models.URLField(max_length=1000),
        ),
    ]
